### ISSUE TITLE
Question about your Project--MyFlowAnalysis

### ISSUE THREAD

**Issue by nuaa040840308** [majestyhao/MyFlowAnalysis#1]
I have downloaded the source code of MyFlowAnalysis. However, I found that some *.jar packets are loss, such as epicc-0.1.jar and Main.jar. Would you like to update your project with them?

**Comment by majestyhao** [comment]
Please refer to https://sites.google.com/site/asergrp/projects/appcontext/appcontext-instruction for those .jar packages.
