### ISSUE TITLE
Errors about the MyTest.java in your PlayContext

### ISSUE THREAD

**Issue by nuaa040840308** [majestyhao/MyFlowAnalysis#2]
![4z7_6 6p5j lz2 6e4 5r](https://cloud.githubusercontent.com/assets/13410137/11212075/75d106fc-8d6e-11e5-8c6e-c2075315c4cf.jpg)

I want to ask how to solve them?

**Comment by majestyhao** [comment]
It is not fully completed yet. Please refer to the latest version.

**Comment by majestyhao** [comment]
btw, ni shi nan hang de yan jiu sheng ba (I will del this sentence once you reply.)

**Comment by nuaa040840308** [comment]
我是南航的本科，现在在国防科大读博。你也是南航的？

**Comment by majestyhao** [comment]
不是，不过我也是在江苏读的本。。
我也是刚入门，你可以单独联系我 haofu AT ucdavis.edu

**Comment by nuaa040840308** [comment]
好的
